apiVersion: v1
kind: Pod
metadata:
  name: sql-test-connection
  namespace: default
  labels:
    azure.workload.identity/use: "true" # Required. Only pods with this label can use workload identity.
spec:
  serviceAccountName: id-afstd-sc2-workload
  containers:
  - name: sqltest
    image: daniellindemann/sql-test-connection
    imagePullPolicy: Always
    env:
    - name: connection-string-beer-rating
      valueFrom:
        secretKeyRef:
          key: connection-string-beer-rating
          name: appsecrets
    volumeMounts:
    - name: appsecrets
      mountPath: "/mnt/appsecrets"
      readOnly: true
    args:
    - "--connectionString"
    - '$(connection-string-beer-rating)'
    - "--wait"
  volumes:
  - name: appsecrets
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "beer-rating-secrets" # [REQUIRED] set it to the name of the the secretProviderClass
