apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: "beer-rating-secrets" # needs to be unique per namespace
spec:
  provider: azure
  secretObjects: # secret objects allow you to create secrets out of the keyvault objects
    - secretName: appsecrets
      data:
        - key: connection-string-beer-rating
          objectName: connection-string-beer-rating
      type: Opaque
  parameters:
    usePodIdentity: "false" # [OPTIONAL] if not provided, will default to "false"
    useVMManagedIdentity: "false" # [OPTIONAL available for version > 0.0.4] if not provided, will default to "false"
    # userAssignedIdentityID: "client_id"     # [OPTIONAL available for version > 0.0.4] use the client id to specify which user assigned managed identity to use. If using a user assigned identity as the VM's managed identity, then specify the identity's client id. If empty, then defaults to use the system assigned identity on the VM
    clientID: "${USER_ASSIGNED_CLIENT_ID}" # [OPTIONAL available for version > 1.1.0] client id of the Azure AD Application or managed identity to use for workload identity
    keyvaultName: "${KEYVAULT_NAME}" # the name of the KeyVault
    cloudName: "" # [OPTIONAL available for version > 0.0.4] if not provided, azure environment will default to AzurePublicCloud
    cloudEnvFileName: "" # [OPTIONAL available for version > 0.0.7] use to define path to file for populating azure environment
    objects: |
      array:
        - |
          objectName: connection-string-beer-rating
          objectType: secret              # object types: secret, key or cert. For Key Vault certificates, refer to https://azure.github.io/secrets-store-csi-driver-provider-azure/configurations/getting-certs-and-keys/ for the object type to use
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty
    tenantId: "${IDENTITY_TENANT}" # The tenant ID of the key vault
